### ISSUE TITLE
Reference object not defined

### ISSUE THREAD

**Issue by sfederici** [djdolphin/Snapin8r2#6]
I get a "Reference object is not defined" error message. Unfortunately github won't allow me to attach the project (neither in sb2 format nor zipped).

**Comment by djdolphin** [comment]
Could you upload the project on Scratch? Also, what browser are you using?

**Comment by djdolphin** [comment]
I've fixed a problem with graphics effects blocks that was likely causing this. Can you try it again?

**Comment by sfederici** [comment]
Thanks djdolphin, it worked like a charm :) (I had the piexelate effect in it indeed). I also found that uploding a zip file in github is a problem only in Chrome, it works fine in Firefox. Unfortunately I found that my 17MB project crashes Firefox. But it works well in Chrome :)

**Comment by djdolphin** [comment]
Great! :D
