### ISSUE TITLE
The error said ReferenceError: obj is not defined

### ISSUE THREAD

**Issue by MINECRAFTJAVA** [djdolphin/Snapin8r2#7]
ReferenceError: obj is not defined

When I tried converting Scratch Project!
Please Help!

**Comment by djdolphin** [comment]
What browser are you using, and what project are you trying to convert?

**Comment by djdolphin** [comment]
Likely a duplicate of #6

**Comment by djdolphin** [comment]
I've fixed a problem with graphics effects blocks that was likely causing this. Can you try it again?

**Comment by MINECRAFTJAVA** [comment]
Ok Thank you

On Wednesday, December 16, 2015, djdolphin <notifications@github.com> wrote:

> I've fixed a problem with graphics effects blocks that was likely causing
> this. Can you try it again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djdolphin/Snapin8r2/issues/7#issuecomment-165298519>.
>


-- 
Niko

**Comment by MINECRAFTJAVA** [comment]
I'll try doing it again

On Wednesday, December 30, 2015, djdolphin <notifications@github.com> wrote:

> Closed #7 <https://github.com/djdolphin/Snapin8r2/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djdolphin/Snapin8r2/issues/7#event-502917999>.
>


-- 
Niko
