### ISSUE TITLE
Click on sprite working differently in Scratch and in Snap

### ISSUE THREAD

**Issue by sfederici** [djdolphin/Snapin8r2#8]
I tested the Snapin8r2 translation of the attached project (https://scratch.mit.edu/projects/92317812) and it works as expected only if I change the option of the menu of the "when I'm" control hat to "pressed". In Scratch indeed the sprite shows a bubble when you stop dragging the (locked) sprite but this doesn't happen in Snap as the option is set to "clicked". I guess you should set the option to "pressed" when you translate the Scratch "when this sprite clicked" control hat?
[drag.zip](https://github.com/djdolphin/Snapin8r2/files/69611/drag.zip)

**Comment by djdolphin** [comment]
Yup, changing this would make sense. I'll do that after school.
